### ISSUE TITLE
Ubuntu 14 Icon issue with location

### ISSUE THREAD

**Issue by midnight109** [rat4/blackcoin#12]
Using Ubuntu 14, downloading Wallet bin64bit from site, while blackcoin is running is makes a small I guess its called a Quick Button, that windows usually puts in the Sys tray, but on my end its placed top left of screen, where the close, mini, maxi, buttons go for the diffrent windows, so cant close windows like webbrowsers while the wallet is running.
![screenshot from 2014-05-23 13 13 53](https://cloud.githubusercontent.com/assets/7682511/3069572/c1280d1c-e29d-11e3-80a9-cdbf9c6b933c.png)

**Comment by mammix2** [comment]
I too can see this on my Ubuntu builds. Did this get sorted, as i cant find anything specific in the code...

**Comment by rat4** [comment]
It's a bug in unity and/or qt.

**Comment by mammix2** [comment]
Yep you're right. Its fixed in Qt5.5. Building on ubuntu using Qt5.5 and the tray icons show correctly
