### ISSUE TITLE
RPC is Broken on Windows

### ISSUE THREAD

**Issue by jprichardson** [rat4/blackcoin#40]
Can you please post another build the RPC fix for Windows? See: http://www.reddit.com/r/blackcoin/comments/2vgzum/rpc_for_blackcoind_in_windows_7/ for more info. 

RPC is broken on Windows and this severely hampers the efforts of 3rd party devs.

For anyone that has the Windows build process already setup, checking out https://github.com/rat4/blackcoin/tree/v1.1.2.1, applying the patch http://www.reddit.com/r/blackcoin/comments/2vgzum/rpc_for_blackcoind_in_windows_7/coj3z77 and subsequently releasing a build wouldn't take too long at all.

cc: @crispybear @xranby

**Comment by crispybear** [comment]
It is already fixed. 
https://github.com/rat4/blackcoin/issues/38
https://github.com/rat4/blackcoin/commit/c974b211f048e33138ad760571e53ef7dee19670

However, the the binaries on blackcoin.co is from December last year, the fix will be included in the next release,

Also, you can compile from the latest source and the problem shouldn't be there.

**Comment by jprichardson** [comment]
Awesome!

However, despite the fact that I'm sure that I could figure out how to build BlackCoin-qt with an investment of time, it's not practical for consumers of my software. We all want BlackCoin to be successful and widely adopted, right? If so, Blackcoin needs a healthy and vibrant 3rd party developer ecosystem. Backporting this patch and updating the binary is trivial for anyone who already has the build system in place. Is this something that you are willing to do? If not, waiting for the next release may be awhile and hence damages the Blackcoin ecosystem. This is critical and needs to be fixed.

Thanks.

**Comment by crispybear** [comment]
I have built the unofficial binaries here: https://github.com/crispybear/crispybear.github.io/tree/master/blackcoin-bin
