### ISSUE TITLE
build win wallet error

### ISSUE THREAD

**Issue by ssdpool** [rat4/blackcoin#47]
./build\bitcoin.o:bitcoin.cpp:(.text+0x2425): undefined reference to `pwalletMain'
./build\bitcoingui.o:bitcoingui.cpp:(.text+0x39e2): undefined reference to `pwalletMain'
./build\bitcoingui.o:bitcoingui.cpp:(.text+0x3a62): undefined reference to `pwalletMain'
./build\bitcoingui.o:bitcoingui.cpp:(.text+0x3b09): undefined reference to `pwalletMain'
./build\bitcoingui.o:bitcoingui.cpp:(.text+0x585c): undefined reference to `pwalletMain'
C:/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: ./build\bitcoingui.o: bad reloc address 0xd60 in section `.rdata'

**Comment by ssdpool** [comment]
wrong .pro modification my mistake issue is mistaked

**Comment by Crazyhead90** [comment]
Huge necro post @ssdpool but do you still remember how you caused./fixed that undefined reference to pwalletmain error? I'm also getting it for a wallet i'm trying to compile

**Comment by Duality-CDOO** [comment]
For some reason I got a notification via emal. You might want to check src/qt/bitcoingui.cpp and see if there is an extern there for pwalletMain, if not, try adding one ;)

**Comment by Duality-CDOO** [comment]
Just add this line: 

extern CWallet* pwalletMain;

**Comment by Crazyhead90** [comment]
![afbeelding](https://user-images.githubusercontent.com/20604229/39869201-f4338db4-545c-11e8-9d33-1a0be0d467a8.png)

There is, so i dont really get why its not seeing it

**Comment by Duality-CDOO** [comment]
Has it got the needed include?

**Comment by Crazyhead90** [comment]
I guess, i'm not sure..

My code is here: https://github.com/Crazyhead90/Linda
( cant seem to make a issue myself to chat there, but maybe you could start one, haha)

I'm using this guide:
https://bitcointalk.org/index.php?topic=1080289.0 to build it via mingw from linux to windows

running the compile-blk.sh which triggers the qt.pro

**Comment by Crazyhead90** [comment]
```
./build/bitcoin.o:bitcoin.cpp:(.text+0x218a): undefined reference to `pwalletMain'
./build/bitcoingui.o:bitcoingui.cpp:(.text+0xb4df): undefined reference to `pwalletMain'
./build/bitcoingui.o:bitcoingui.cpp:(.text+0xb543): undefined reference to `pwalletMain'
./build/bitcoingui.o:bitcoingui.cpp:(.text+0xb59e): undefined reference to `pwalletMain'
./build/bitcoingui.o:bitcoingui.cpp:(.text+0xbd54): undefined reference to `pwalletMain'
./build/bitcoingui.o:bitcoingui.cpp:(.text+0xbd5d): more undefined references to `pwalletMain' follow
./build/miner.o:miner.cpp:(.text+0x3d7d): undefined reference to `CBlock::SignBlock(CWallet&, long long)'
./build/rpcdump.o:rpcdump.cpp:(.text+0x1194): undefined reference to `pwalletMain'
./build/rpcdump.o:rpcdump.cpp:(.text+0x11dc): undefined reference to `pwalletMain'
./build/rpcdump.o:rpcdump.cpp:(.text+0x120b): undefined reference to `pwalletMain'
./build/rpcdump.o:rpcdump.cpp:(.text+0x1244): undefined reference to `pwalletMain'
./build/rpcdump.o:rpcdump.cpp:(.text+0x1250): undefined reference to `pwalletMain'
./build/rpcdump.o:rpcdump.cpp:(.text+0x1294): more undefined references to `pwalletMain' follow
/mnt/mxe/usr/i686-w64-mingw32.static/lib/libdb_cxx.a(os_pid.o):os_pid.c:(.text+0x25): undefined reference to `pthread_self'
collect2: error: ld returned 1 exit status
Makefile.Release:533: recipe for target 'release/Linda-qt.exe' failed
make: *** [release/Linda-qt.exe] Error 1
root@ubuntu:/mnt/Linda# 

```

Is the full error code
(the pthread i can fix by adding -pthread in the qt.pro windows libs)

**Comment by volbil** [comment]
@Crazyhead90 any luck with this issue?

**Comment by ProjectHelixCoin** [comment]
@volbil No, but i gave up and moved on a long time ago

**Comment by Crazyhead90** [comment]
@volbil No but i gave up and moved on a long time ago

**Comment by volbil** [comment]
I see, thanks anyway @Crazyhead90 
Btw, have you figure out better way to make Windows build?

**Comment by Crazyhead90** [comment]
I went for a fork of the dash project chain which supports gitian building. With a simple command it compiles for Linux, windows and ios.

**Comment by volbil** [comment]
@Crazyhead90 I figure it out, for some reason `ENABLE_WALLET` flag cause problems with Windows build, so I just removed it from source code, and it worked lol
