### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by microlost** [rat4/blackcoin#49]
:-1: error: cannot find -lboost_thread_win32-mgw48-mt-s-1_55
collect2.exe:-1: error: error: ld returned 1 exit status

**Comment by rat4** [comment]
Provide to qmake the BOOST_LIB_SUFFIX and BOOST_THREAD_LIB_SUFFIX that are appropriate to your build environment.

**Comment by mozzria** [comment]
:-1: error: cannot find -li2psam

**Comment by mozzria** [comment]
error: cannot find -li2psam

**Comment by rat4** [comment]
@mozzria we never had a link to i2psam. Please make sure that you're trying to build the code from this repository.

**Comment by microlost** [comment]
Now the dependency library in the blackcoin.pro was setting like this:

win32 {
    BOOST_LIB_SUFFIX=-mgw48-mt-s-1_55
    BOOST_INCLUDE_PATH=C:/deps/boost_1_55_0
    BOOST_LIB_PATH=C:/deps/boost_1_55_0/stage/lib
    BDB_INCLUDE_PATH=C:/deps/db-4.8.30.NC/build_unix
    BDB_LIB_PATH=C:/deps/db-4.8.30.NC/build_unix
    OPENSSL_INCLUDE_PATH=C:/deps/openssl-1.0.1g/include
    OPENSSL_LIB_PATH=C:/deps/openssl-1.0.1g
    MINIUPNPC_INCLUDE_PATH=C:/deps/
    MINIUPNPC_LIB_PATH=C:/deps/miniupnpc
    QRENCODE_INCLUDE_PATH=C:/deps/qrencode-3.4.3
    QRENCODE_LIB_PATH=C:/deps/qrencode-3.4.3/.libs
}

With the above environment configuration, other coin to compile successfully, in addition to blackcoin.

can you tell my how to set the environment variable of BOOST_THREAD_LIB_SUFFIX ?

**Comment by rat4** [comment]
Well, if you modify the pro file, you also can change
BOOST_THREAD_LIB_SUFFIX there.
