### ISSUE TITLE
nStakeMinAge still referenced in GetWeight

### ISSUE THREAD

**Issue by SpicyDrumSticks** [rat4/blackcoin#51]
nStakeMinAge still referenced in GetWeight https://github.com/rat4/blackcoin/blob/protocolv3/src/kernel.cpp#L13-L20

GetWeight is referencded when comparing to GetStakeSplitAge in https://github.com/rat4/blackcoin/blob/protocolv3/src/wallet.cpp#L1948

GetStakeSplitAge is only referenced there.
GetStakeSplitAge is declared here https://github.com/rat4/blackcoin/blob/protocolv3/src/wallet.cpp#L28

Those are the only things stopping it from not using nStakeMinAge at all when its only using protocolv3.

**Comment by lencoin** [comment]
I guess a workaround would be to make it ask "if (nCredit > GetStakeCombineThreshold())" when its using protocolv3 instead of "if (GetWeight(nBlockTime, (int64_t)txNew.nTime) < GetStakeSplitAge())".
