### ISSUE TITLE
UPNP

### ISSUE THREAD

**Issue by bearsylla** [rat4/blackcoin#54]
The binaries might require recompile.

http://talosintel.com/reports/TALOS-2015-0035/

**Comment by bearsylla** [comment]
what do you think of disabling it as per  https://github.com/rubycoinorg/rubycoin/commit/bd4a3e57f53f1d4caa2f0aa6ea27f86958c3454a

**Comment by rat4** [comment]
Whilst I don't like miniupnpc's code, I also don't like to disable UPNP.
