### ISSUE TITLE
blackcoin client 1.2.1 (qt, windows8) crashes on importprivkey

### ISSUE THREAD

**Issue by blkmaarx** [rat4/blackcoin#61]
When I use importprivkey <key> , and I import a correct key, the blackcoin-qt crashes. After a force- restart (kill process with task manager), the key is imported in the wallet and the address shown.

When I import an incorrect key, there is no crash. It shows error message like expected.

**Comment by rat4** [comment]
If you kill it in the task manager, it hasn't crashed. Probably you do import with rescan (default) and don't wait long enough. The bigger blockchain the more time rescan needs.

**Comment by blkmaarx** [comment]
Basically the client becomes unresponsive after importprivkey. I can kill
it with task manager or I can kill it after "this program does not respond"
notification on Windows.

2016-01-19 14:00 GMT+01:00 Pavel Vasin <notifications@github.com>:

**Comment by blkmaarx** [comment]
I will try import and wait for a while / dont do anything and report back.

2016-01-19 14:56 GMT+01:00 Maarten Visser <mpvisser91@gmail.com>:

**Comment by blkmaarx** [comment]
Client becomes responsive after ~4 minutes but new address seems not listed
in GUI until restart of client. Thanks

2016-01-19 14:57 GMT+01:00 Maarten Visser <mpvisser91@gmail.com>:
